modLoader = "javafml"
loaderVersion = "[16,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheRandomLabs/Nyan-Cow/issues"

[[mods]]

modId = "nyancow"
version = "${file.jarVersion}"
displayName = "Nyan Cow"
updateJSONURL = "https://raw.githubusercontent.com/TheRandomLabs/Nyan-Cow/misc/versions.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/nyan-cow"
logoFile = "logo.png"
authors = "TheRandomLabs"
description = '''
Nyan Cow, the best mod ever written for Minecraft, no doubt.
'''
